coverage:
  status:
    project:
      contracts:
        target: auto
        paths:
          - "cadence/contracts/**"
    patch:
      contracts:
        target: auto
        paths:
          - "cadence/contracts/**"


