coverage:
  status:
    project:
      contracts:
        target: 80%
        paths:
          - "cadence/contracts/**"
    patch:
      contracts:
        target: 80%
        paths:
          - "cadence/contracts/**"


